### ISSUE TITLE
create reusable nash functions

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/gootstrap#1]
@katcipis What do you think of creating functions that we can reuse when creating more advanced setups?

For example, the file coverage.sh could declare a function called `cover` that I can use from anywhere to get the coverage of any project. Example below:

```sh
λ> import gootstrap/cover
λ> cover("github.com/NeowayLabs/nash")
/* shows coverage here */
λ> cover("github.com/c0defellas/enzo")
/* shows coverage here */
```

**Comment by katcipis** [comment]
@tiago4orion sounds nice, but for my workflow I would probably use it from inside the project directory (using current working directory).

**Comment by i4ki** [comment]
Then maybe we can split the functions in `cover(dir)` and `coverProject(prj)`. This way you can call `cover(".")` from inside Makefile.
